version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - "27017:27017"
  api:
    container_name: jacqui-api
    build: ./api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
  app:
    container_name: jacqui-app
    build: ./app
    ports:
      - "80:8080"
